### ISSUE TITLE
only 900 out of 3700 components are cross-shop

### ISSUE THREAD

**Issue by Artimunor** [pcbuilderapp/pcbuilder#15]
Detection of the same components across multiple shops works but only partially.

Only 900 out of 3700 components are cross-shop is shown by the following query:

SELECT com.name, count(p.id) num_products 
FROM component com, product p
WHERE com.id = p.component_id 
GROUP BY com.name 
ORDER BY num_products;

Find out why most of the components are not linked between shops

**Comment by MehmetSo** [comment]
1060 components of 39xx
