### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by MehmetSo** [pcbuilderapp/pcbuilder#18]
6.6 Rate limiting
6.6.1 Quality attribute
Integrity
6.6.2 Description
To prevent a service-consumer to overload the backend, a rate limit should be implemented.
6.6.3 Indicator
The maximum number of request needs to be determined from normal use and enforced in production.
6.6.4 Measurement
Simulate several normal usage scenarios and measure the amount of request within a set amount of time. Create an upper bound based on these measurements and test/refine them.
6.6.5 Norm
Normal load is assumed.

**Comment by Artimunor** [comment]
also rate limmits crawler product adds
