### ISSUE TITLE
Price history date filtering

### ISSUE THREAD

**Issue by MehmetSo** [pcbuilderapp/pcbuilder#19]
6.8 Price history can be filtered by using a date range
6.8.1 Quality attribute
Performance
6.8.2 Description
The backend server should provide a date range, on which price history can be filtered in order to reduce performance strain on the server, when large sets of pricing history are accumulated.
6.8.3 Indicator
When retrieving the pricing history of a given product, it should be limited by a start and an end date. 
6.8.4 Measurement
When showing pricing history data screen loading times are measured and deemed acceptable if below 1 second.
6.8.5 Norm
Performance can be guaranteed even when large sets of pricing data are accumulated.

**Comment by Artimunor** [comment]
backend supports selecting pricehistories by dateranges, frontend gets pricehistory of last month by default
