### ISSUE TITLE
matching bug

### ISSUE THREAD

**Issue by sladage** [pcbuilderapp/pcbuilder#21]
Deze config geeft geen mogelijke moederborden meer. Ook herselecteren van case kan niet meer.

![untitled-1](https://cloud.githubusercontent.com/assets/4071431/22397094/f4bf6dc4-e569-11e6-8b03-edefe8eac86e.png)

**Comment by Artimunor** [comment]
heeft dat ooit wel gekund dan? met die combinatie?

**Comment by Artimunor** [comment]
hij lijkt te liggen aan de case, als er eerst een case selected wordt, is het niet meer mogelijk een moederbord te selecten, haal je de case weg dan kan het weer.
